<a href="https://colab.research.google.com/github/NS-Nakharin/229352-Statistical-Learning-Labs/blob/main/Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [3]:
a = torch.tensor(2)
print(a)

b = torch.tensor(3)
print(a + b)

tensor(2)
tensor(5)


### Convert a tensor to scalar

In [5]:
c = b.item()
print(c)

3


### Creating 2D tensor

In [6]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [7]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [8]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [9]:
torch.cuda.is_available()

True

In [10]:
C.device

device(type='cpu')

In [11]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [12]:
D.device

device(type='cuda', index=0)

In [14]:
C + D

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [16]:
#D.numpy()
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [17]:
D ** 2

tensor([[ 1,  4],
        [25, 36]], device='cuda:0')

In [18]:
D - 2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [19]:
D.cpu() * np.array([1,2])

/tmp/ipython-input-1707415638.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1,2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [20]:
A = torch.tensor([[4 ,5],
                  [8, 9]])
B = torch.tensor([[1 ,4],
                  [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [21]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [22]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [23]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [24]:
# tensor ที่มีแต่เลข 0
a = torch.zeros(1, 2, 3)
a

# tensor ที่มีแต่เลข 1
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [25]:
# Identity matrix
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [26]:
# Random
R1 = torch.rand(2, 3) # Uniform dist.
R1

tensor([[0.4199, 0.8840, 0.1590],
        [0.0600, 0.3614, 0.4892]])

In [27]:
R2 = torch.randn(2, 3) # Normal dist.
R2

tensor([[ 1.6081,  2.7391,  0.0966],
        [-0.5743, -0.5324, -1.3049]])

In [28]:
# vector เรียงลำดับกัน
a = torch.arange(1, 10, 2)
a

tensor([1, 3, 5, 7, 9])

## Tensor's shape

In [29]:
A.shape

torch.Size([2, 2])

In [30]:
A.size()

torch.Size([2, 2])

### Checking the shape of a tensor

In [31]:
u = torch.arange(6)
print(u.shape)
u

torch.Size([6])


tensor([0, 1, 2, 3, 4, 5])

### Changing the shape of a tensor

In [32]:
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [33]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [34]:
a = torch.arange(4)
b = torch.arange(4) + 1
a, b

(tensor([0, 1, 2, 3]), tensor([1, 2, 3, 4]))

In [35]:
c = torch.stack([a, b], axis = 0) #stack แบบแถว
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [36]:
d = torch.stack([a, b], axis = 1) #stack แบบหลัก
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [37]:
# concatenate
e = torch.cat([a, b], axis = 0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [38]:
# concatenate (Dimension out of range (expected to be in range of [-1, 0], but got 1))
f = torch.cat([a, b], axis = 1)
f

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [39]:
A = torch.zeros(1, 2, 3)

In [40]:
# Remove 1st axis
B = A.squeeze() # defaut คือแกนที่มี 1 แถว
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [41]:
C = B.unsqueeze(axis = 0)
C.shape

torch.Size([1, 2, 3])

## Indexing

In [42]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [43]:
P[0:2, 0:2]
P[[0, 1, 2], [0, 1, 2]]

tensor([ 0,  5, 10])

In [44]:
# Inverse
torch.inverse(torch.tensor([[1.0, 2.0], [1.0, 4.0]]))

tensor([[ 2.0000, -1.0000],
        [-0.5000,  0.5000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [63]:
# Create three random  N(0,1)  tensors: X
X = torch.randn(200, 7)
print('X.shape :', X.shape)

# Create three random  N(0,1)  tensors: b
b = torch.randn(8, 1)
print('b.shape :', b.shape)

# Create three random  N(0,1)  tensors: e
e = torch.randn(200, 1)
print('e.shape :', e.shape)

X.shape : torch.Size([200, 7])
b.shape : torch.Size([8, 1])
e.shape : torch.Size([200, 1])


In [64]:
# Create a tensor that contains only 1's with shape (200, 1).
ones = torch.ones(200, 1)
print(ones.shape)

torch.Size([200, 1])


In [65]:
# Modify tensor X by adding the tensor in 2. as the first column
X = torch.cat([ones, X], axis = 1)
print(X.shape)
print(X)

torch.Size([200, 8])
tensor([[ 1.0000,  1.5088,  0.9196,  ..., -0.0301, -0.9678, -0.8479],
        [ 1.0000,  2.5736,  0.3549,  ...,  0.5405, -1.3498, -0.1868],
        [ 1.0000, -0.7080, -1.0059,  ...,  1.3207, -0.8047,  1.4049],
        ...,
        [ 1.0000, -0.6950, -0.2726,  ...,  0.6580,  0.4358, -0.5264],
        [ 1.0000,  1.2404,  1.1662,  ..., -1.0399, -1.4976,  1.4152],
        [ 1.0000,  0.8062, -0.8412,  ..., -1.0109,  0.0059, -0.5246]])


In [66]:
# Compute y using the following formula
y = torch.mm(X, b) + e

In [67]:
# Fit a linear regression to the data X and y and obtain a tensor of estimated coefficient b_hat
X_inv = torch.inverse(X.t() @ X)
b_hat = X_inv @ X.t() @ y
print(b_hat)

tensor([[ 0.0440],
        [ 0.4572],
        [ 0.3601],
        [ 0.1557],
        [-0.4179],
        [ 0.8500],
        [-0.0832],
        [-0.6134]])


In [68]:
# Compute the predictions
y_hat = X @ b_hat
print(y_hat.shape)

torch.Size([200, 1])


In [69]:
# Convert both y and y_hat from tensor to Numpy array and calculate MSE

# Convert to numpy
y = y.numpy()
y_hat = y_hat.numpy()


# Calculate MSE
mse = np.mean((y - y_hat)**2)
print('MSE:',mse)

MSE: 1.0348887
